#ifndef DATABASE_TABLES_BASE_UNDEF_CLEANUP_HPP_INCLUDED
#define DATABASE_TABLES_BASE_UNDEF_CLEANUP_HPP_INCLUDED

#undef OPT_WRAPPER
#undef OPT_NONE

#undef NOT_NULL
#undef AUTO_INCREMENT
#undef SIZE_ID
#undef TYPE_ID
#undef SIZE
#undef TYPE
#undef MAX_ARGUMENTS

#undef VMAX
#undef VMAX_OP

#undef SET_TUPLE_SIZE_PRED
#undef SET_TUPLE_SIZE_OP
#undef SET_TUPLE_SIZE_M
#undef SET_TUPLE_SIZE_F
#undef SET_TUPLE_SIZE

#undef DEFL_NULL
#undef UNSPECIFIED_TYPE
#undef UNSPECIFIED_SIZE

#undef EXTRACT_TYPE
#undef EXTRACT_TYPE_IMPL
#undef EXTRACT_TYPE_PRED

#undef EXTRACT_TYPE_SIZE
#undef EXTRACT_TYPE_SIZE_IMPL
#undef EXTRACT_TYPE_SIZE_PRED

#undef IS_IN_FIELD_TUPLE
#undef IS_IN_FIELD_TUPLE_FOLD_OP

#undef SEQUENCE_FACTORY_0
#undef SEQUENCE_FACTORY_1
#undef SEQUENCE_FACTORY_0_END
#undef SEQUENCE_FACTORY_1_END

#undef NAMESPACE_SEQ_EACH
#undef NAMESPACE_COLON_SEQ_EACH
#undef NAMESPACE_SEQ
#undef NAMESPACE_COLON_SEQ
#undef CLOSING_CURLY

#undef TABLE_FIELD
#undef TABLE_FIELD_INITIALIZER
#undef TABLE_CONSTRUCTOR_PARAMETERS
#undef TABLE_ATTRIBUTES

#undef DECLARE_TABLE_IMPL
#undef DECLARE_TABLE

#endif // DATABASE_TABLES_BASE_UNDEF_CLEANUP_HPP_INCLUDED
